# 문자열 심화

## 대소문자 변환

In [1]:
text='Hello Python'

print(text)

print(text.upper())
print(text.lower())

Hello Python
HELLO PYTHON
hello python

## 공백 제거

In [2]:
name="            python          "

print(f"원본 {name}")
print(f"정리 후 {name.strip()}")

#변수와 String 비교
print("공백이 있을 때 비교",name=="python")
print("공백 제거 후 비교",name.strip()=="python")

원본             python
정리 후 python
공백이 있을 때 비교 False
공백 제거 후 비교 True

## 문자열 바꾸기

In [3]:
sentence="파이썬을 배우고 있습니다. 파이썬은 재밌습니다."

new_sentence=sentence.replace("파이썬","Python")

print("원본:",sentence)
print("수정:",new_sentence)

원본: 파이썬을 배우고 있습니다. 파이썬은 재밌습니다.
수정: Python을 배우고 있습니다. Python은 재밌습니다.

In [4]:
price="1,500,000원"
clean_price=price.replace(",","").replace("원","")

print(int(clean_price))

1500000

## 문자열 나누기

In [5]:
words="사과 바나나 포도 딸기"

word_list=words.split()
print(word_list)

['사과', '바나나', '포도', '딸기']

In [6]:
words="사과,바나나,포도,딸기"

word_list=words.split(",")
print(word_list,len (word_list))

['사과', '바나나', '포도', '딸기'] 4

## 문자열 자르기

In [7]:
phone="010-1234-5678"

#앞에서 세글자
print(phone[0:3])
#가운데 네글자
print(phone[4:8])
#마지막 네글자
print(phone[-4:])

010
1234
5678

## 문제
이메일 주소에서 아이디와 도메인을 분리하세요

In [8]:
email="12345@emali.dalim.ac.kr"

parts=email.split("@")
user_id=parts[0]
domain=parts[1]

print("이메일:",email)
print("아이디:",user_id)
print("도메인:",domain)

이메일: 12345@emali.dalim.ac.kr
아이디: 12345
도메인: emali.dalim.ac.kr

## 문자열 검색

In [9]:
review="이 제품은 정말 좋아요! 배송도 빠르고 품질도 훌륭합니다"

print("좋아요 포함:","좋아요"in review)
print("나빠요 포함:","나빠요"in review)

if "좋아요" in review or "훌륭" in review:
    print("긍정적 리뷰")
else:
    print("부정적 리뷰")

좋아요 포함: True
나빠요 포함: False
긍정적 리뷰

## 함수 심화

## 함수 기본값

In [10]:
def greet(name, greeting="환영합니다"):
    print(f"{name}님, {greeting}")

greet("대림대")
greet("대림대","안녕하세요")

대림대님, 환영합니다
대림대님, 안녕하세요

In [11]:
#할인율 계산
#discount: 0.0 ~ 1.0(0% ~ 100%)

def calcaulate_price(price,discount=0):
    discounted=price * (1-discount)
    return discounted

print(f"기본 가격: {calcaulate_price(10000)}원") 
print(f"기본 가격: {calcaulate_price(10000,0.1)}원")

기본 가격: 10000원
기본 가격: 9000.0원

## 함수에서 여러값 반환하기

In [12]:
#최솟값과 최댓값을 동시에 반환하는 함수

def min_max(numbers):
    minimum=min(numbers)
    maximum=max(numbers)
    return minimum, maximum

scores=[10,20,30,40,50,60,70,80]

low,high=min_max(scores)

print(min_max(scores))
print("최솟값: ",low)
print("최대값: ",high)

(10, 80)
최솟값:  10
최대값:  80

## 문제
class_scores = [45,62,78,55,90,83,71,66,48,95]
1. 성적 분석 함수 생성
2. 아래와 같은 로그 출력
    - 평균: x.x 점 (소수점 첫번째 자리 까지만 출력)
    - 최고점: xx점
    - 최저점: xx점
    - 합격(60점 이상): x명

In [13]:
def smin_smax(numbers):
    sminimum=min(numbers)
    smaximum=max(numbers)
    return sminimum, smaximum

def savg(number):
    sums=0
    count=0
    for i in number[0:]:
        sums+=i
        count+=1
    student_avg=sums/count

    return student_avg

def s_success(number):
    s=0
    for i in number:
        if i>=60:
            s+=1
    student_success=s
    return student_success
    
class_scores=[45,62,78,55,90,83,71,66,48,95]

low,high=smin_smax(class_scores)

avg=savg(class_scores)

suc=s_success(class_scores)

print(f"평균값 :{avg:.1f}점")
print(f"최솟값 :{low}점")
print(f"최대값 :{high}점")
print(f"합격(60점 이상): {suc}명")

평균값 :69.3점
최솟값 :45점
최대값 :95점
합격(60점 이상): 7명

## Pandas 심화

In [14]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [15]:
#학생 데이터
grade_data={
    "name":["kim","lee","park","choi","jung","min"],
    "korean":[88,72,95,65,80,91],
    "math":[75,90,65,85,77,82],
    "english":[82,88,76,70,95,78],
}
grade_df=pd.DataFrame(grade_data)
grade_df

   name  korean  math  english
0   kim      88    75       82
1   lee      72    90       88
2  park      95    65       76
3  choi      65    85       70
4  jung      80    77       95
5   min      91    82       78

## 정렬하기

In [16]:
print("---국어 점수 낮은 순---")
print (grade_df.sort_values("korean"))
print()
print("---수학 점수 낮은 순---")
print (grade_df.sort_values("math",ascending=False))

---국어 점수 낮은 순---
   name  korean  math  english
3  choi      65    85       70
1   lee      72    90       88
4  jung      80    77       95
0   kim      88    75       82
5   min      91    82       78
2  park      95    65       76

---수학 점수 낮은 순---
   name  korean  math  english
1   lee      72    90       88
3  choi      65    85       70
5   min      91    82       78
4  jung      80    77       95
0   kim      88    75       82
2  park      95    65       76

## 새로운 열 추가하기

In [17]:
grade_df["average"] = (grade_df["korean"] +  grade_df["math"] + grade_df["english"]) / 3

grade_df["average"]=grade_df["average"].round(1)
grade_df

   name  korean  math  english  average
0   kim      88    75       82     81.7
1   lee      72    90       88     83.3
2  park      95    65       76     78.7
3  choi      65    85       70     73.3
4  jung      80    77       95     84.0
5   min      91    82       78     83.7

In [18]:
grade_df["grade"]=grade_df["average"].apply;{
    lambda x:"A" if x >= 80 else "B"
}

grade_df

,name,korean,math,english,average,grade
0,kim,88,75,82,81.7,<bound method Series.apply of 0 81.7\n1 ...
1,lee,72,90,88,83.3,<bound method Series.apply of 0 81.7\n1 ...
2,park,95,65,76,78.7,<bound method Series.apply of 0 81.7\n1 ...
3,choi,65,85,70,73.3,<bound method Series.apply of 0 81.7\n1 ...
4,jung,80,77,95,84.0,<bound method Series.apply of 0 81.7\n1 ...
5,min,91,82,78,83.7,<bound method Series.apply of 0 81.7\n1 ...

## 그룹별 통계

In [19]:
group_avg=grade_df.groupby("grade")["average"].mean()
print("등급별 평균:")
print(group_avg)

등급별 평균:
grade
<bound method Series.apply of 0    81.7\n1    83.3\n2    78.7\n3    73.3\n4    84.0\n5    83.7\nName: average, dtype: float64>    80.783333
Name: average, dtype: float64

In [20]:
#응용-회사 부서별 급여 파악
employee_data={
    "name":["kim","lee","park","choi","jung","min"],
    "department":["개발","마케팅","개발","인사","마케팅","인사"],
    "salary":[4200,3500,4800,3200,3800,5000],
} 
emp_df=pd.DataFrame(employee_data)
emp_df

#부서별 평균 급여
dept_avg=emp_df.groupby("department")["salary"].mean()
print("---부서별 평균 급여---")
print(dept_avg.round(0))
print()
print("---부서별 인원 수---")
dept_count=emp_df.groupby("department")["name"].count()
print(dept_count)

---부서별 평균 급여---
department
개발     4500.0
마케팅    3650.0
인사     4100.0
Name: salary, dtype: float64

---부서별 인원 수---
department
개발     2
마케팅    2
인사     2
Name: name, dtype: int64